### ISSUE TITLE
Reduce the uncommon characters in Chinese and Korean

### ISSUE THREAD

**Issue by GrimPixel** [ogallagher/wordsearch_generator#32]
In the demo, most characters in Chinese and Korean are obsolete so those characters don't make fun at all.

**Comment by ogallagher** [comment]
Convenient [Korean syllable relative frequency data](http://nlp.kookmin.ac.kr/data/syldown.html), [가나다순 results download](http://nlp.kookmin.ac.kr/data/syl-1.txt).

**Comment by GrimPixel** [comment]
For Chinese, there are lists of frequent characters.
For People's Republic of China https://zh.wikisource.org/wiki/%E9%80%9A%E7%94%A8%E8%A7%84%E8%8C%83%E6%B1%89%E5%AD%97%E8%A1%A8
For Republic of China https://zh.wikisource.org/wiki/%E5%B8%B8%E7%94%A8%E5%9C%8B%E5%AD%97%E6%A8%99%E6%BA%96%E5%AD%97%E9%AB%94%E8%A1%A8

**Comment by ogallagher** [comment]
Adding a `alphabet_char_sets/` directory, with `\n` delimited character list files whose name can be used as an alternative item in `ranges` to an embedded code point array.

**Comment by ogallagher** [comment]
> For Chinese, there are lists of frequent characters.
> For People's Republic of China https://zh.wikisource.org/wiki/%E9%80%9A%E7%94%A8%E8%A7%84%E8%8C%83%E6%B1%89%E5%AD%97%E8%A1%A8
> For Republic of China https://zh.wikisource.org/wiki/%E5%B8%B8%E7%94%A8%E5%9C%8B%E5%AD%97%E6%A8%99%E6%BA%96%E5%AD%97%E9%AB%94%E8%A1%A8

Corresponding character set files:
- [zh_taiwan_top_8105.txt](https://github.com/ogallagher/wordsearch_generator/blob/main/alphabet_charsets/zh_taiwan_top_8105.txt)
- [zh_china_top_4808.txt](https://github.com/ogallagher/wordsearch_generator/blob/main/alphabet_charsets/zh_china_top_4808.txt)

**Comment by ogallagher** [comment]
- [ ] add charset control to webpage component

Use a similar widget to the controls I made for alphabet and example config file.

**Comment by ogallagher** [comment]
- [ ] test that example config file with pre selected charset (ex. zh-4808) loads properly.

**Comment by ogallagher** [comment]
@GrimPixel as of now, the functionality should exist to handle better character sets for Chinese and Korean. Both cases still err on the side of using too many characters, but further improvement should just be tuning/customization of what's already been done.

**Comment by GrimPixel** [comment]
I wonder if other languages can also implement letter frequency when generating the game.
