### ISSUE TITLE
Support DSV format words files

### ISSUE THREAD

**Issue by GrimPixel** [ogallagher/wordsearch_generator#34]
I wish I could use my own DSV files (first column the word, other columns the hint) to practice, instead of json, because it's easier to create.

For the original attributes in the json, size would be determined by a configuration file; language can be omitted; title can be also omitted and substituted by the file name

**Comment by ogallagher** [comment]
@GrimPixel In a DSV file dictionary, you would only have 2 columns, right? And DSV being delimiter-separated-values?

Concerning other config file changes:

- Why omit the language?
- I will keep the title attribute, but can use the file name if it's not present.

**Comment by GrimPixel** [comment]
I thought the language can be omitted if the file is in the folder with that language as its name.
